import type {Metadata} from "next";

import '@/_common/_theme/css-reset.css';
import '@/_common/_theme/global.css';
import 'terminal.css'

import Header from "@/_components/header";
import Footer from "@/_components/footer";

import styles from './styles.module.css'
import { spaceGrotesk } from "@/_components/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({children }: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        <Header/>
        <div className={styles.mainContainer}>{children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
